var pages = [ 
"https://carijandaonline.blogspot.com/",
"https://carijandaonline.blogspot.com/p/melayu-girl.html",
"https://carijandasingle.blogspot.com/",
"https://carijandasingle.blogspot.com/p/beautiful-tiktoker.html",
"https://infojandacantik.blogspot.com/",
"https://infojandacantik.blogspot.com/p/info-janda-cantik.html",
"https://jandacantikkaya.blogspot.com",
"https://jandacantikkaya.blogspot.com/p/janda-single.html",
"https://jandacarilelaki.blogspot.com/",
"https://jandacarilelaki.blogspot.com/p/janda-cari-lelaki.html",
"https://jandacurhatonline.blogspot.com",
"https://jandacurhatonline.blogspot.com/p/janda-curhat-online.html",
"https://jandamudajamannow.blogspot.com",
"https://jandamudajamannow.blogspot.com/p/janda-muda-jaman-now.html",
"https://jandasinglecantik.blogspot.com",
"https://jandasinglecantik.blogspot.com/p/janda-single-cantik.html",
"https://jandasurga.blogspot.com",
"https://jandasurga.blogspot.com/p/portube-girls.html",
"https://jodohjandakembang.blogspot.com",
"https://jodohjandakembang.blogspot.com/p/jodoh-janda-kembang.html",
"https://jomblocurhatonline.blogspot.com",
"https://jomblocurhatonline.blogspot.com/p/jomblo-curhat-online.html",
"https://jutaanjanda.blogspot.com",
"https://jutaanjanda.blogspot.com/p/hot-mommy.html",
"https://kasihjanda.blogspot.com",
"https://kasihjanda.blogspot.com/p/viral-today.html",
"https://kumpulanjandabohay.blogspot.com",
"https://kumpulanjandabohay.blogspot.com/p/kumpulan-janda-bohay.html",
"https://nomerjanda.blogspot.com",
"https://nomerjanda.blogspot.com/p/nomer-janda.html",
"https://randacantik.blogspot.com",
"https://randacantik.blogspot.com/p/randa-cantik.html",
"https://sejutajanda.blogspot.com",
"https://sejutajanda.blogspot.com/p/pretty-girls.html",
"https://sijandacantik.blogspot.com",
"https://sijandacantik.blogspot.com/p/si-janda-cantik.html",
"https://sijandakembang.blogspot.com",
"https://sijandakembang.blogspot.com/p/si-janda-kembang.html",
"https://surgajanda.blogspot.com",
"https://surgajanda.blogspot.com/p/ngewe-janda.html",
];
function randomPage() { 
return pages[Math.round(Math.random() * (pages.length - 1))]; 
} 
location.href= randomPage(); 
